version: 2
jobs:
  b1:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: ls
  b2:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "hello"

workflows:
  version: 2
  one_and_two:
    jobs:
      - b1
      - b2