# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/
    steps:
      - checkout
      - run: pwd
      - run: echo "Here we go"

  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #           - v1-dependencies-{{ checksum "package.json" }}
  #           # fallback to using the latest cache if no exact match is found
  #           - v1-dependencies-

  #     - run: yarn install

  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

  #     # run tests!
  #     - run: yarn test


  # # https://circleci.com/docs/2.0/google-auth/
  # # https://circleci.com/docs/2.0/google-container-engine/
  # # https://cloud.google.com/container-registry/docs/pushing
  # push-image:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
  #     - run: docker build --rm=false -t eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
  #     - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
  #     - run: gcloud --quiet config set project ${GCP_PROJECT}
  #     - run: gcloud docker -- push eu.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1